POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "userName":"prueba3",
  "email": "PRUEBA4@gmail.com",
  "password": "contras234"
}


###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "userName":"54646dfg",
  "email": "PRUEBA7@gmail.com",
  "password": " Contras1234"
}

###

POST http://localhost:3000/api/habit/personalizado
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJQUlVFQkEzQGdtYWlsLmNvbSIsInVzZXJOYW1lIjoicHJ1ZWJhMyIsImlhdCI6MTc0NjY3MTgwOSwiZXhwIjoxNzQ2Njc1NDA5fQ.pskNDDs_-F25-1LGnsL8u7p72fTjV8mU57sDawNllfs

{
  "userId": 1,
  "name": "Correr4",
  "description": "desc",
  "frequency": {
    "type": "weekly",
    "days": ["tuesday"]
  },
  "icon": "../img/gestorhabitos/correr.png",
  "startDate": "2025-04-26T00:00:00.000Z",
  "fieldValues": {"unit": "min", "value": "30"},
  "reminder": true
}

###

GET http://localhost:3000/api/inicio/principalScr
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJQUlVFQkEzQGdtYWlsLmNvbSIsInVzZXJOYW1lIjoicHJ1ZWJhMyIsImlhdCI6MTc0NjY2NjM1NywiZXhwIjoxNzQ2NjY5OTU3fQ.CcMblXWu1NDtbUrCp4lJfS_A1JPSlfGgNWjCdjmu3OU

###
GET http://localhost:3000/api/inicio/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJQUlVFQkEzQGdtYWlsLmNvbSIsInVzZXJOYW1lIjoicHJ1ZWJhMyIsImlhdCI6MTc0NjY2NjM1NywiZXhwIjoxNzQ2NjY5OTU3fQ.CcMblXWu1NDtbUrCp4lJfS_A1JPSlfGgNWjCdjmu3OU

###
GET http://localhost:3000/api/auth/deleteAcc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJQUlVFQkE0QGdtYWlsLmNvbSIsInVzZXJOYW1lIjoicHJ1ZWJhMyIsImlhdCI6MTc0NjY3MjM2MSwiZXhwIjoxNzQ2Njc1OTYxfQ.gw95kwv-MKR-cRHGjHkIfz_5K0Q2sbhYf2nxVmU8p8Y
Content-Type: application/json

{
  "email": "PRUEBA4@gmail.com",
  "password": "contras234"
}


//prueba de subir habitos de todos los usuarios a habitLogTraking
###
POST http://localhost:3000/api/cargarHabitos/generateTodayHabits

###
POST http://localhost:3000/api/inicio/actualizarLogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJQUlVFQkE0QGdtYWlsLmNvbSIsInVzZXJOYW1lIjoicHJ1ZWJhMyIsImlhdCI6MTc0NjY3MjM2MSwiZXhwIjoxNzQ2Njc1OTYxfQ.gw95kwv-MKR-cRHGjHkIfz_5K0Q2sbhYf2nxVmU8p8Y
Content-Type: application/json

{
  "userHabitId": 17,
  "date": "2025-05-10T00:00:00.000Z",
  "status": "complete"
}